Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands
end

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_App/app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true
end

Music_App/app/models/user.rb
class User < ApplicationRecord


    validates :email, :session_token, uniqueness: true, presence: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }

    after_initialize :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return user if user && user.is_password?(password)
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token #to return it
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        obj = BCrypt::Password.new(self.password_digest)
        obj.is_password?(password)
    end


end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        if logged_in?
            current_user.reset_session_token!
        end

        session[:session_token] = nil
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end
end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])
        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = ['Stupid mistake!']
            render :edit
        end

    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])

        if user
            login!(user)
            redirect_to user_url(user)
        else
            flash.now[:errors] = ["Invalid credentails"]
            render :new
        end
    end

    def new
        render :new
    end

    def destroy
        logout!
        flash[:success] = ["Successfully logged out."]
        redirect_to new_session_url
    end

end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end


    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper

    def auth_token
        "<input type='hidden' name='authenticity_token' vlaue='#{form_authenticity_token}'>".html_safe
    end

end

Music_App/app/views/bands/edit.html.erb
<h1>Edit Band page</h1>

<form action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="_method" value="patch">

    <%= auth_token %>

    <label>Edit info:
        <input type="text" name="band[name]" value="<%= @band.name%>">
    </label>
    <input type="submit" value="Edit!">
</form>

Music_App/app/views/bands/index.html.erb
<h1>All Bands</h1>

    <%= auth_token %>
<ul>

    <% @bands.each do |band| %>
        <li> <%= band.name %>
        <a href="<%= band_url(band)%>">Show Page</a>
        </li>
    <% end %>
</ul>

Music_App/app/views/bands/new.html.erb
<h1>New bands page</h1>

<form action="<%=bands_url%>" method="post">

    <%= auth_token %>

    <label>New band!
        <input type="text" name="band[name]" value="">
    </label>
    <input type="submit" value="Submit">
</form>

Music_App/app/views/bands/show.html.erb
<h1>Band Page</h1>

<form action="<%= band_url(@band) %>" method="get">
    
    <%= auth_token %>
    
    <label> Band Name:
        <%= @band.name %>
    </label>

    <a href="<%= edit_band_url(@band) %>">Edit info</a>
    

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
      <h1>MusicApp</h1>
  </header>
    <% if logged_in? %>
        <h2>Welcome</h2>

        <form action="<%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Log Out">        
        </form>
      <% else %>
          <a class="url_tag" href="<%= new_session_url %>">Log In</a>
          <a class="url_tag" href="<%= new_user_url %>">Sign Up</a>
      <% end %>

    <%if flash[:errors]%>
      <ul>
        <%flash[:errors].each do |error|%>
          <li><%=error %></li>
        <%end%>
      </ul>
    <%end%>

     <%if flash[:success]%>
      <ul>
        <%flash[:success].each do |msg|%>
          <li><%=msg %></li>
        <%end%>
      </ul>
    <%end%>

    <%= yield %>
  </body>
</html>

Music_App/app/views/users/new.html.erb
<h1>User sign up page</h1>

<form action="<%=users_url%>" method="post">

    <%= auth_token %>

    <label>Username: 
        <input type="text" name="user[email]" value="">
    </label>
    <label>Password: 
        <input type="password" name="user[password]" value="">
    </label>
    <input type="submit" value="Submit">
</form>

Music_App/app/views/users/show.html.erb
<h1>Show Page</h1>

<form action="<%= user_url(@user) %>" method="get">
    
    <%= auth_token %>
    
    <label>Email:
        <%= @user.email %>
    </label>
    
</form>